version: '3.8'

services:
  generate_commit:
    build: .
    environment:
      - GIT_LOG
      - GIT_DIFF
    volumes:
      - .:/usr/src/app  # Mount the commit builder directory
      - ${PWD}:/usr/src/project  # Mount the current project directory where the command is run
    working_dir: /usr/src/project
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    tty: true
