version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    command: python tools/generate_commit/generate_commit.py

  tests:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONPATH=/usr/src/app
    command: ./run_tests.sh --verbose

