name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and run tests
      run: |
        docker-compose build
        docker-compose run tests
    - name: Check coverage
      run: |
        if ! grep -q "100%" htmlcov/index.html; then
          echo "Coverage is not 100%"
          exit 1
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and run app
      run: |
        docker-compose build
        docker-compose up -d app